### PR TITLE
refactor: Refactor tag and branch validation logic

### PR DESCRIPTION
**Pull request by DerekMaggio**
# Overview

Refactor to use `git ls-remote` with subprocess instead of hitting Github API

# Changelog

See commits

# Review requests

This is a better than hitting the API right?

# Risk assessment

Low

### CODE REVIEW

**Review by sfoster1 — APPROVED** [review]
Yeah if it works it works. It doesn't really look like gitpython is doing a whole lot for you, it's not even formatting the return, so subprocess probably works fine too, but there's no problem using it.

**Comment by DerekMaggio** [comment]
@sfoster1, https://github.com/Opentrons/opentrons-emulation/pull/268/commits/3d8fd0134dd7c229c12ae66f2335c412652e05b9 this better?

**Review by fsinapi — APPROVED** [review]
really nice

**Comment by sfoster1** [comment]
Yeah, really nice!

**Pull request merged**
