### PR TITLE
Fix: fix typos in readme  for App-UI env

### PR DESCRIPTION
**Pull request by koji**
# Overview
Fixed typos in readme for app-ui env.
Also updated the branch name.

# Changelog
- update readme (APPS_AND_UI_SETUP.md)

# Review requests
- changes are correct 

# Risk assessment
low

### CODE REVIEW

**Review by DerekMaggio — APPROVED** [review]

**Comment by DerekMaggio** [comment]
Ignore the failing tests. They are not the result of this PR.

**Comment by koji** [comment]
@DerekMaggio 
Could you merge this PR into `main`? 
Seems still I only have read access.

**Comment by DerekMaggio** [comment]
Let me fix that so you can merge

**Comment by DerekMaggio** [comment]
I think I fixed it. Can you try again?

**Pull request merged**
