### PR TITLE
feat: Add build step to install clang and boost

### PR DESCRIPTION
**Pull request by DerekMaggio**
# Overview

Adding build step to cache clang and boost

# Changelog

- Create GetClangAndBoost_CMakeLists.txt
- Override default ot3-firmware CMakeLists.txt and build in `ot3-firmware-deps-getter`
- Copy /ot3-firmware/stm32-tools over to `ot3-firmware-builder`

# Review requests

Is there a better way to do this instead of overriding the CMakeLists.txt in ot3-firmware?
It would be nice if I could use this to download clang and boost for both `opentrons-modules` and `ot3-firmware`

I would ideally like to add these in the `cpp-base` layer

# Risk assessment

Low

### CODE REVIEW

**Review by sfoster1 — CHANGES_REQUESTED** [review]
I think a good way to do this might be to run `cmake --preset=cross` and `cmake --preset=cross-pipettes`, but then `rm -rf ./build-*` and _then_ cache. that way you'll have all of `stm32-tools` prepopulated. 

Plus this way the actual `cmake --preset=cross` in the build stage will download new versions of those deps if necessary without breaking the build.

**Comment by DerekMaggio** [comment]
Would it be the same thing for `opentrons-modules` as well? 
`cmake --preset=stm32-cross`

Also can I just use `host` instead of `cross` since it will be built in a Linux environment

**Comment by sfoster1** [comment]
> Would it be the same thing for `opentrons-modules` as well? `cmake --preset=stm32-cross`
> 
> Also can I just use `host` instead of `cross` since it will be built in a Linux environment

Oh, yeah, definitely to both

**Review by sfoster1 — APPROVED** [review]
Nice, should be way faster

**Pull request merged**
