### PR TITLE
feat: Add binding of custom folders to VM (RET-325)

### PR DESCRIPTION
**Pull request by DerekMaggio**
# Overview

Add support for binding user defined folders to Virtual Machine through config file

# Changelog

- Added optional SharedFolder Pydantic model to [settings_models.py](https://github.com/Opentrons/opentrons-emulation/pull/29/files#diff-1a2c6e8f2e3d30cda3ef9d700471a9c383340874b9673f102d636f116da5a6faR45-R49)
- Inside of VirtualMachineCommandCreator add shared folders to json output
- In Vagrantfile parse all shared folders and add them to VM
- Added env vars to [dry run option](https://github.com/Opentrons/opentrons-emulation/pull/29/files#diff-b02788c3ae8b8113c56f46ebc5731c201cc0b67d438984b441b14b6a8a0bce2c)
- Refactored so all shared folders are bound using `SHARED_FOLDERS` setting in generated setting.json
- All shared folders now are added at `/home/vagrant`
- CLI is now smart enough to use bound folder paths if you are inside VM, and your local paths if you are not
- Documented [here](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/1044217859/Creating+Configuration+File)

# Review requests

None, created [RET-360](https://opentrons.atlassian.net/browse/RET-360)

# Risk assessment

Low, new feature no one is needing. 
Tested that specifying nothing causes no exceptions

### CODE REVIEW

**Comment by DerekMaggio** [comment]
Example configuration file with `shared-folders` key
```
{
    "global-settings": {
        "default-folder-paths": {
            "opentrons": "/home/derek-maggio/Documents/repos/opentrons",
            "ot3-firmware": "/home/derek-maggio/Documents/repos/ot3-firmware",
            "modules": "/home/derek-maggio/Documents/repos/opentrons-modules"
        }
    },

    "emulation-settings": {
        "source-download-locations": {
            "heads": {
                "opentrons": "https://github.com/Opentrons/opentrons/archive/refs/heads/edge.zip",
                "ot3-firmware": "https://github.com/Opentrons/ot3-firmware/archive/refs/heads/main.zip",
                "modules": "https://github.com/Opentrons/opentrons-modules/archive/refs/heads/edge.zip"
            },
            "commits": {
                "opentrons": "https://github.com/Opentrons/opentrons/archive/{{commit-sha}}.zip",
                "ot3-firmware": "https://github.com/Opentrons/ot3-firmware/archive/{{commit-sha}}.zip",
                "modules": "https://github.com/Opentrons/opentrons-modules/archive/{{commit-sha}}.zip"
            }
        }
    },

    "virtual-machine-settings": {
        "dev-vm-name": "Development VM",
        "prod-vm-name": "Production VM",
        "vm-memory": 4096,
        "vm-cpus": 2,
        "num-socket-can-networks": 1,
        "shared-folders": [
            {"host-path": "/home/derek-maggio/Desktop/shared_folder", "vm-path":  "/home/shared_folder"}
        ]
    },

    "aws-ecr-settings": {}
}
```

**Comment by DerekMaggio** [comment]
@sfoster1 @amitlissack there are still a few things I need to do before I mark this ready for review. 
But can you evaluate the error handling I am talking about in my Review Requests and let me know if you have any suggestions? 

Thanks

**Comment by DerekMaggio** [comment]
> @sfoster1 @amitlissack there are still a few things I need to do before I mark this ready for review. But can you evaluate the error handling I am talking about in my Review Requests and let me know if you have any suggestions?
> 
> Thanks

Created [RET-360](https://opentrons.atlassian.net/browse/RET-360) for this, and I am going to say it is outside the scope of this PR

**Review by amitlissack — APPROVED** [review]

**Review by sfoster1 — APPROVED** [review]
lgtm!

**Pull request merged**
