### PR TITLE
chore: Add CPX setup instructions

### PR DESCRIPTION
**Pull request by DerekMaggio**
# Overview

Add setup instructions for CPX

# Changelog

- Add link in main README to CPX_SETUP.md
- Clean up CPX_SETUP.md by giving summaries of what each step is doing 

# Review requests

@shlokamin can you test this and also select someone from your team to run through this? 

# Risk assessment

None

### CODE REVIEW

**Comment by DerekMaggio** [comment]
Need to update command to `docker exec -it cpx-ot2-ot2 bash -c "/entrypoint.sh build && /entrypoint.sh run"`

**Review by sakibh — CHANGES_REQUESTED** [review]
Tested this on my M1 Mac. The container name to start the robot server was `cpx-ot2-ot2` and not `ot2-with-all-modules-otie` (mentioned in the above comment as well).

The `modules` end point does return all the module information as expected, however, changing the `displayName` in `modules.py` to something else (e.g. `BOOOOOOP`) and then rebuilding/restarting the dev server did not update the `displayName` when hitting the end point.

**Comment by DerekMaggio** [comment]
> The modules end point does return all the module information as expected, however, changing the displayName in modules.py to something else (e.g. BOOOOOOP) and then rebuilding/restarting the dev server did not update the displayName when hitting the end point.

Well that's annoying, I will look into. 

Thank you for testing!!!

**Comment by DerekMaggio** [comment]
Updated docker command to be correct. 
Went through steps to reproduce error @sakibh was seeing. Not able to reproduce. 
Going to setup a debugging session to get to the bottom of it

**Review by jerader — COMMENTED** [review]
Sorry this took me awhile to leave feedback! Other than the incorrect container name, the few things that I had a hard time with had nothing to do with the emulator directly. But I recommend having some more info on them to help folks out like me who don't really use python:

1. making it clear that python environment needs to be set up
2. linking a quick overview and guide to Postman as well as adding more steps to what to do when you are in Postman.

**Comment by DerekMaggio** [comment]
> Sorry this took me awhile to leave feedback! Other than the incorrect container name, the few things that I had a hard time with had nothing to do with the emulator directly. But I recommend having some more info on them to help folks out like me who don't really use python:
> 
> 1. making it clear that python environment needs to be set up
> 2. linking a quick overview and guide to Postman as well as adding more steps to what to do when you are in Postman.

@jerader Let me know if you think the update [Required Software](https://github.com/Opentrons/opentrons-emulation/tree/CPX-README-update#required-software) section of the README and[ replacing Postman usage with a curl command](https://github.com/Opentrons/opentrons-emulation/blob/CPX-README-update/docs/team_specific_setup/CPX_SETUP.md#build-and-start-robot-server) is clearer

**Comment by DerekMaggio** [comment]
@sakibh, Josh ran the steps on his M1 without any issues.
I am going to merge this and we can diagnose your issues separately

**Review by sakibh — APPROVED** [review]

**Pull request merged**
